DROP TABLE IF EXISTS Calls;

CREATE TABLE IF NOT EXISTS Calls (
  c_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  c_phone VARCHAR(30) NOT NULL,
  c_recording_url VARCHAR(100) NOT NULL,
  c_created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
)