// Generated by Wrangler on Tue Sep 10 2024 21:54:37 GMT+0800 (Singapore Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	API_HOST: "https://the-obsessed-planter.ozk-zhengkai.workers.dev";
	DB: D1Database;
}
